version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2204:edge
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            npx envinfo
            docker build -t gengjiawen/node-build .
            docker build -t gengjiawen/node-build:source -f Dockerfile.source .
            docker build -t gengjiawen/node-build:remote -f Dockerfile.remote .
      - run:
          name: Docker Info
          command: |
            docker run --rm --name lo gengjiawen/node-build:remote bash -c "envinfo"
      - run:
          name: Push
          command: |
            docker login -u gengjiawen -p $DOCKER_PASS
            docker push gengjiawen/node-build
            docker push gengjiawen/node-build:remote
            docker push gengjiawen/node-build:source

workflows:
  version: 2
  build:
    jobs:
      - test
  monthly:
    jobs:
      - test
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
              only:
                - master
